name: Build

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --verbose
    - name: Upload artifact
      # if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v2
      with:
        name: git-absorb-${{ matrix.os }}
        path: |
          target/debug/git-absorb
          target/debug/git-absorb.exe
